version: '2'
services:
  fluxoWeb:
    container_name: simple_instance
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # image: simple_instance:latest
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
     - .:/usr/share/nginx/html
     - ./nginx.conf:/etc/nginx/nginx.conf
